//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualizerUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualizerUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column ähnelt.
        /// </summary>
        public static string CB_CHART_TYPES_COLUMN {
            get {
                return ResourceManager.GetString("CB_CHART_TYPES_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        public static string CB_CHART_TYPES_LINE {
            get {
                return ResourceManager.GetString("CB_CHART_TYPES_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cost Amount ähnelt.
        /// </summary>
        public static string CB_KEY_FIGURE_COST_AMOUNT {
            get {
                return ResourceManager.GetString("CB_KEY_FIGURE_COST_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sales Amount ähnelt.
        /// </summary>
        public static string CB_KEY_FIGURE_SALES_AMOUNT {
            get {
                return ResourceManager.GetString("CB_KEY_FIGURE_SALES_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string CB_PERIOD_TYPE_DAY {
            get {
                return ResourceManager.GetString("CB_PERIOD_TYPE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        public static string CB_PERIOD_TYPE_MONTH {
            get {
                return ResourceManager.GetString("CB_PERIOD_TYPE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quarter ähnelt.
        /// </summary>
        public static string CB_PERIOD_TYPE_QUARTER {
            get {
                return ResourceManager.GetString("CB_PERIOD_TYPE_QUARTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        public static string CB_PERIOD_TYPE_WEEK {
            get {
                return ResourceManager.GetString("CB_PERIOD_TYPE_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string CB_PERIOD_TYPE_YEAR {
            get {
                return ResourceManager.GetString("CB_PERIOD_TYPE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual ähnelt.
        /// </summary>
        public static string CHART_COST_AMT_ACT_LEGEND {
            get {
                return ResourceManager.GetString("CHART_COST_AMT_ACT_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected ähnelt.
        /// </summary>
        public static string CHART_COST_AMT_EXP_LEGEND {
            get {
                return ResourceManager.GetString("CHART_COST_AMT_EXP_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cost Amount ähnelt.
        /// </summary>
        public static string CHART_COST_AMT_TITLE {
            get {
                return ResourceManager.GetString("CHART_COST_AMT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        public static string CHART_COST_AMT_TOT_LEGEND {
            get {
                return ResourceManager.GetString("CHART_COST_AMT_TOT_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual ähnelt.
        /// </summary>
        public static string CHART_SALES_AMT_ACT_LEGEND {
            get {
                return ResourceManager.GetString("CHART_SALES_AMT_ACT_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sales Amount ähnelt.
        /// </summary>
        public static string CHART_SALES_AMT_TITLE {
            get {
                return ResourceManager.GetString("CHART_SALES_AMT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Company specified ähnelt.
        /// </summary>
        public static string ERROR_COMPANY_MISSING {
            get {
                return ResourceManager.GetString("ERROR_COMPANY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have choosen an option which is not valid or not implemented! ähnelt.
        /// </summary>
        public static string ERROR_INVALID_OPTION {
            get {
                return ResourceManager.GetString("ERROR_INVALID_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No NAV Database specified ähnelt.
        /// </summary>
        public static string ERROR_NAV_DATABASE_MISSING {
            get {
                return ResourceManager.GetString("ERROR_NAV_DATABASE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No NAV Server specified ähnelt.
        /// </summary>
        public static string ERROR_NAV_SERVER_MISSING {
            get {
                return ResourceManager.GetString("ERROR_NAV_SERVER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during updating chart! Please update Visualizer Database. ähnelt.
        /// </summary>
        public static string ERROR_UPDATE_CHART {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Visualizer Database specified ähnelt.
        /// </summary>
        public static string ERROR_VISUALIZER_DATABASE_MISSING {
            get {
                return ResourceManager.GetString("ERROR_VISUALIZER_DATABASE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Visualizer Server specified ähnelt.
        /// </summary>
        public static string ERROR_VISUALIZER_SERVER_MISSING {
            get {
                return ResourceManager.GetString("ERROR_VISUALIZER_SERVER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAV Visualizer ähnelt.
        /// </summary>
        public static string MAIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string MSG_TITLE {
            get {
                return ResourceManager.GetString("MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualizer Database updated ähnelt.
        /// </summary>
        public static string MSG_UPDATE_DONE {
            get {
                return ResourceManager.GetString("MSG_UPDATE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chart Type: ähnelt.
        /// </summary>
        public static string MW_CHART_TYPE_LABEL {
            get {
                return ResourceManager.GetString("MW_CHART_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company: ähnelt.
        /// </summary>
        public static string MW_COMPANY_LABEL {
            get {
                return ResourceManager.GetString("MW_COMPANY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End date: ähnelt.
        /// </summary>
        public static string MW_END_DATE_LABEL {
            get {
                return ResourceManager.GetString("MW_END_DATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Figure: ähnelt.
        /// </summary>
        public static string MW_KEY_FIGURE_LABEL {
            get {
                return ResourceManager.GetString("MW_KEY_FIGURE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAV Database: ähnelt.
        /// </summary>
        public static string MW_NAV_DATABASE_LABEL {
            get {
                return ResourceManager.GetString("MW_NAV_DATABASE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAV Server: ähnelt.
        /// </summary>
        public static string MW_NAV_SERVER_LABEL {
            get {
                return ResourceManager.GetString("MW_NAV_SERVER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Period Type: ähnelt.
        /// </summary>
        public static string MW_PERIOD_TYPE_LABEL {
            get {
                return ResourceManager.GetString("MW_PERIOD_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start date: ähnelt.
        /// </summary>
        public static string MW_START_DATE_LABEL {
            get {
                return ResourceManager.GetString("MW_START_DATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Database ähnelt.
        /// </summary>
        public static string MW_UPDATE_DATABASE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("MW_UPDATE_DATABASE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualizer Database: ähnelt.
        /// </summary>
        public static string MW_VISUALIZER_DATABASE_LABEL {
            get {
                return ResourceManager.GetString("MW_VISUALIZER_DATABASE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualizer Server: ähnelt.
        /// </summary>
        public static string MW_VISUALIZER_SERVER_LABEL {
            get {
                return ResourceManager.GetString("MW_VISUALIZER_SERVER_LABEL", resourceCulture);
            }
        }
    }
}
